"""empty message

Revision ID: 77b2233fdcf2
Revises: 
Create Date: 2022-07-31 14:59:41.700730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b2233fdcf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('hash', sa.String(length=8), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('password_hashed', sa.String(length=240), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('paste')
    # ### end Alembic commands ###
