"""empty message

Revision ID: 89af91d1575b
Revises: 77b2233fdcf2
Create Date: 2022-08-04 19:27:43.684899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89af91d1575b'
down_revision = '77b2233fdcf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_letter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_letter')
    # ### end Alembic commands ###
